name: 'feed ci'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/setup-icu@v1
      - name: gist feed
        uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          url: |
            https://gist.github.com/Neko7sora.atom
          file: 'README.md'
          timezone: 'Asia/Tokyo'
          format: '- ${year}/${02month}/${02day} - [${title}](${url})'
          start_flag: "<!-- gist feed start -->"
          end_flag: "<!-- gist feed end -->"
      - name: articles feed
        uses: sarisia/actions-readme-feed@v1
        id: articles
        with:
          url: |
            https://newsletters.neko7sora.site?format=rss
            https://note.com/neko7sora/rss
            https://zenn.dev/neko7sora/feed
            https://qiita.com/Neko7sora/feed
            https://neko7sora.blogspot.com/feeds/posts/default
          file: 'README.md'
          timezone: 'Asia/Tokyo'
          format: '- ${year}/${02month}/${02day} - [${title}](${url})'
          start_flag: "<!-- articles feed start -->"
          end_flag: "<!-- articles feed end -->"
      - name: push to master
        if: (steps.feed.outputs.changed == true || steps.articles.outputs.changed == true)
        id: commit
        uses: sarisia/actions-commit@master
        with:
          message: "[skip ci] docs: update feed"
